
CREATE TABLE Owner (
owner_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
email VARCHAR(255) NOT NULL,
phone VARCHAR(15) NOT NULL,
password VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
state VARCHAR(30) NOT NULL,
zipcode VARCHAR(20) NOT NULL
);




CREATE TABLE Pet (
pet_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(30) NOT NULL,
animal VARCHAR(50) DEFAULT 'Dog',
birthdate DATE NOT NULL,
owner_id INT NOT NULL,
insurance_id INT NOT NULL
);



CREATE TABLE Document (
doc_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
file_type VARCHAR(255) NOT NULL,
file_name VARCHAR(255) NOT NULL,
owner_id INT NOT NULL,
created_at DATETIME NOT NULL,
file_upload VARCHAR(1023),
visit_id INT,
pet_id INT NOT NULL
);


CREATE TABLE insurance (
insurance_id INT AUTO_IMCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
phone VARCHAR(15) NOT NULL
);

CREATE TABLE Visit (
visit_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
date DATE NOT NULL,
pet_id INT NOT NULL,
vet_id INT NOT NULL,
cost INT NOT NULL,
paid INT NOT NULL,
service_id INT NOT NULL
);

CREATE TABLE Service (
service_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
type TEXT
);

CREATE TABLE Vet (
vet_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
name VARCHAR(60) NOT NULL,
address VARCHAR(255) NOT NULL,
state VARCHAR(30) NOT NULL,
zipcode VARCHAR(30) NOT NULL,
phone VARCHAR(30) NOT NULL,
email VARCHAR(255) NOT NULL
);